# Generated by Django 2.0.5 on 2018-05-28 12:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seo title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='Seo title')),
                ('slug', models.SlugField(max_length=180)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Pages',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
